### PR TITLE
add map type conversion

### PR DESCRIPTION
**Pull request by manmat**
## Description

Adding support for the complex type `map`. The `map` type is documented [here](https://avro.apache.org/docs/current/spec.html#Maps), the conversion standard to BigQuery type is documented [here](https://cloud.google.com/bigquery/docs/loading-data-cloud-storage-avro#:~:text=types%20are%20ignored.-,map%3CT%3E,-RECORD).

## Type of Change

- [ ] Bug Fix
- [ ] New Feature
- [x] Breaking Change
- [ ] Refactor
- [ ] Documentation
- [ ] Other (please describe)

## Checklist

- [x] I have read the [contributing guidelines](https://github.com/wayfair-incubator/avro-to-bigquery/blob/main/CONTRIBUTING.md)
- [x] Existing issues have been referenced (where applicable)
- [x] I have verified this change is not present in other open pull requests
- [x] Functionality is documented
- [x] All code style checks pass
- [x] New code contribution is covered by automated tests
- [x] All new and existing tests pass

### CODE REVIEW

**Comment by manmat** [comment]
@crdoconnor Is there anything I can do to make the process of reviewing this PR easier and faster?

**Comment by manmat** [comment]
Maybe @matsmaiwald knows more?

**Comment by crdoconnor** [comment]
My apologies I should have looked at this earlier.

**Comment by crdoconnor** [comment]
LGTM i think it just needs blacking.

**Comment by manmat** [comment]
It looks like black failed not because of formatting issues but some other problems?

**Comment by crdoconnor** [comment]
Thank you @manmat ! This should be published on version 0.4.0. Let me know if there are any issues.

**Pull request merged**
